table Categories
	column category_name
		dataType: string
		sourceColumn: category_name
	column items
		dataType: int64
		sourceColumn: items
	column orders
		dataType: int64
		sourceColumn: orders
	column unique_customers
		dataType: int64
		sourceColumn: unique_customers
	column merchandise_value_brl
		dataType: double
		sourceColumn: merchandise_value_brl
	column avg_item_price_brl
		dataType: double
		sourceColumn: avg_item_price_brl
	column late_delivery_pct
		dataType: double
		sourceColumn: late_delivery_pct
	column avg_review_score
		dataType: double
		sourceColumn: avg_review_score

	measure 'Category GMV' = SUM('Categories'[merchandise_value_brl])
		formatString: R$ #,##0.00
	measure 'Category Orders' = SUM('Categories'[orders])
		formatString: #,0

	partition Categories = m
		mode: import
		source =
			let
				Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/Jorgoluka100/uni_projects/main/projects/business_intelligence_showcase/data/category_performance.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"category_name", type text}, {"items", Int64.Type}, {"orders", Int64.Type}, {"unique_customers", Int64.Type}, {"merchandise_value_brl", type number}, {"avg_item_price_brl", type number}, {"late_delivery_pct", type number}, {"avg_review_score", type number}})
			in
				Typed
