table KPI
	column commercial_orders
		dataType: int64
		sourceColumn: commercial_orders
	column unique_customers
		dataType: int64
		sourceColumn: unique_customers
	column merchandise_value_brl
		dataType: double
		sourceColumn: merchandise_value_brl
	column avg_order_value_brl
		dataType: double
		sourceColumn: avg_order_value_brl
	column repeat_customer_pct
		dataType: double
		sourceColumn: repeat_customer_pct
	column late_delivery_pct
		dataType: double
		sourceColumn: late_delivery_pct
	column avg_review_score
		dataType: double
		sourceColumn: avg_review_score
	column on_time_review_score
		dataType: double
		sourceColumn: on_time_review_score
	column late_review_score
		dataType: double
		sourceColumn: late_review_score

	measure 'Commercial Orders' = MAX('KPI'[commercial_orders])
		formatString: #,0
	measure 'Unique Customers' = MAX('KPI'[unique_customers])
		formatString: #,0
	measure 'Marketplace GMV' = MAX('KPI'[merchandise_value_brl])
		formatString: R$ #,##0.00
	measure 'Average Order Value' = MAX('KPI'[avg_order_value_brl])
		formatString: R$ #,##0.00
	measure 'Repeat Customer Rate' = DIVIDE(MAX('KPI'[repeat_customer_pct]), 100)
		formatString: 0.00%
	measure 'Late Delivery Rate' = DIVIDE(MAX('KPI'[late_delivery_pct]), 100)
		formatString: 0.00%
	measure 'Average Review Score' = MAX('KPI'[avg_review_score])
		formatString: 0.00
	measure 'Delivery Review Gap' = MAX('KPI'[on_time_review_score]) - MAX('KPI'[late_review_score])
		formatString: 0.00

	partition KPI = m
		mode: import
		source =
			let
				Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/Jorgoluka100/uni_projects/main/projects/business_intelligence_showcase/data/kpis.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"commercial_orders", Int64.Type}, {"unique_customers", Int64.Type}, {"merchandise_value_brl", type number}, {"avg_order_value_brl", type number}, {"repeat_customer_pct", type number}, {"late_delivery_pct", type number}, {"avg_review_score", type number}, {"on_time_review_score", type number}, {"late_review_score", type number}})
			in
				Typed
