table Monthly
	column order_month
		dataType: dateTime
		sourceColumn: order_month
	column orders
		dataType: int64
		sourceColumn: orders
	column unique_customers
		dataType: int64
		sourceColumn: unique_customers
	column merchandise_value_brl
		dataType: double
		sourceColumn: merchandise_value_brl
	column freight_value_brl
		dataType: double
		sourceColumn: freight_value_brl
	column avg_order_value_brl
		dataType: double
		sourceColumn: avg_order_value_brl
	column late_delivery_pct
		dataType: double
		sourceColumn: late_delivery_pct
	column avg_review_score
		dataType: double
		sourceColumn: avg_review_score

	measure 'Monthly GMV' = SUM('Monthly'[merchandise_value_brl])
		formatString: R$ #,##0.00
	measure 'Monthly Orders' = SUM('Monthly'[orders])
		formatString: #,0

	partition Monthly = m
		mode: import
		source =
			let
				Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/Jorgoluka100/uni_projects/main/projects/business_intelligence_showcase/data/monthly_performance.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"order_month", type date}, {"orders", Int64.Type}, {"unique_customers", Int64.Type}, {"merchandise_value_brl", type number}, {"freight_value_brl", type number}, {"avg_order_value_brl", type number}, {"late_delivery_pct", type number}, {"avg_review_score", type number}})
			in
				Typed
