table States
	column customer_state
		dataType: string
		sourceColumn: customer_state
	column orders
		dataType: int64
		sourceColumn: orders
	column unique_customers
		dataType: int64
		sourceColumn: unique_customers
	column merchandise_value_brl
		dataType: double
		sourceColumn: merchandise_value_brl
	column avg_order_value_brl
		dataType: double
		sourceColumn: avg_order_value_brl
	column late_delivery_pct
		dataType: double
		sourceColumn: late_delivery_pct
	column avg_review_score
		dataType: double
		sourceColumn: avg_review_score

	measure 'State GMV' = SUM('States'[merchandise_value_brl])
		formatString: R$ #,##0.00
	measure 'State Orders' = SUM('States'[orders])
		formatString: #,0

	partition States = m
		mode: import
		source =
			let
				Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/Jorgoluka100/uni_projects/main/projects/business_intelligence_showcase/data/state_performance.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"customer_state", type text}, {"orders", Int64.Type}, {"unique_customers", Int64.Type}, {"merchandise_value_brl", type number}, {"avg_order_value_brl", type number}, {"late_delivery_pct", type number}, {"avg_review_score", type number}})
			in
				Typed
