table CategoryPerformance

	measure 'Category GMV' = SUM(CategoryPerformance[merchandise_value_brl])
		formatString: R$ #,##0.00

	measure 'Category Orders' = SUM(CategoryPerformance[orders])
		formatString: #,##0

	measure 'Average Review' = AVERAGE(CategoryPerformance[average_review_score])
		formatString: 0.00

	column category_name
		dataType: string
		summarizeBy: none
		sourceColumn: category_name

	column orders
		dataType: int64
		sourceColumn: orders

	column merchandise_value_brl
		dataType: double
		sourceColumn: merchandise_value_brl

	column average_review_score
		dataType: double
		sourceColumn: average_review_score

	column merchandise_value_rank
		dataType: int64
		sourceColumn: merchandise_value_rank

	partition CategoryPerformance = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataRoot & "\\category_performance.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"category_name", type text}, {"orders", Int64.Type}, {"merchandise_value_brl", type number}, {"average_review_score", type number}, {"merchandise_value_rank", Int64.Type}})
			in
				Typed
