table DeliveryImpact

	measure 'Delivered Orders' = SUM(DeliveryImpact[orders])
		formatString: #,##0

	measure 'Delivery GMV' = SUM(DeliveryImpact[merchandise_value_brl])
		formatString: R$ #,##0.00

	measure 'Average Review by Delay' = DIVIDE(SUMX(DeliveryImpact, DeliveryImpact[average_review_score] * DeliveryImpact[orders]), SUM(DeliveryImpact[orders]))
		formatString: 0.00

	measure 'One Star Review Rate' = DIVIDE(SUMX(DeliveryImpact, DeliveryImpact[one_star_review_pct] * DeliveryImpact[orders]), SUM(DeliveryImpact[orders]) * 100)
		formatString: 0.00%

	measure 'Five Star Review Rate' = DIVIDE(SUMX(DeliveryImpact, DeliveryImpact[five_star_review_pct] * DeliveryImpact[orders]), SUM(DeliveryImpact[orders]) * 100)
		formatString: 0.00%

	column delivery_bucket
		dataType: string
		summarizeBy: none
		sourceColumn: delivery_bucket

	column orders
		dataType: int64
		sourceColumn: orders

	column merchandise_value_brl
		dataType: double
		sourceColumn: merchandise_value_brl

	column average_days_late
		dataType: double
		sourceColumn: average_days_late

	column average_review_score
		dataType: double
		sourceColumn: average_review_score

	column one_star_review_pct
		dataType: double
		sourceColumn: one_star_review_pct

	column five_star_review_pct
		dataType: double
		sourceColumn: five_star_review_pct

	column delivered_order_share_pct
		dataType: double
		sourceColumn: delivered_order_share_pct

	partition DeliveryImpact = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataRoot & "\\analysis_delivery_impact.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"delivery_bucket", type text}, {"orders", Int64.Type}, {"merchandise_value_brl", type number}, {"average_days_late", type number}, {"average_review_score", type number}, {"one_star_review_pct", type number}, {"five_star_review_pct", type number}, {"delivered_order_share_pct", type number}})
			in
				Typed
