table ExecutiveKPIs

	measure 'Commercial Orders' = MAX(ExecutiveKPIs[commercial_orders])
		formatString: #,##0

	measure 'Unique Customers' = MAX(ExecutiveKPIs[unique_customers])
		formatString: #,##0

	measure 'Merchandise Value' = MAX(ExecutiveKPIs[merchandise_value_brl])
		formatString: R$ #,##0.00

	measure 'Average Order Value' = MAX(ExecutiveKPIs[average_order_value_brl])
		formatString: R$ #,##0.00

	measure 'Repeat Customer %' = MAX(ExecutiveKPIs[repeat_customer_pct]) / 100
		formatString: 0.00%

	measure 'Top 10 Seller Share %' = MAX(ExecutiveKPIs[top_ten_seller_share_pct]) / 100
		formatString: 0.00%

	column commercial_orders
		dataType: int64
		summarizeBy: none
		sourceColumn: commercial_orders

	column unique_customers
		dataType: int64
		summarizeBy: none
		sourceColumn: unique_customers

	column merchandise_value_brl
		dataType: double
		summarizeBy: none
		sourceColumn: merchandise_value_brl

	column average_order_value_brl
		dataType: double
		summarizeBy: none
		sourceColumn: average_order_value_brl

	column repeat_customer_pct
		dataType: double
		summarizeBy: none
		sourceColumn: repeat_customer_pct

	column top_ten_seller_share_pct
		dataType: double
		summarizeBy: none
		sourceColumn: top_ten_seller_share_pct

	partition ExecutiveKPIs = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataRoot & "\\executive_kpis.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"commercial_orders", Int64.Type}, {"unique_customers", Int64.Type}, {"merchandise_value_brl", type number}, {"average_order_value_brl", type number}, {"repeat_customer_pct", type number}, {"top_ten_seller_share_pct", type number}})
			in
				Typed
