table MonthlyPerformance

	measure 'Total GMV' = SUM(MonthlyPerformance[merchandise_value_brl])
		formatString: R$ #,##0.00

	measure 'Total Orders' = SUM(MonthlyPerformance[orders])
		formatString: #,##0

	measure 'Average Order Value' = AVERAGE(MonthlyPerformance[average_order_value_brl])
		formatString: R$ #,##0.00

	column order_month
		dataType: dateTime
		summarizeBy: none
		sourceColumn: order_month

	column orders
		dataType: int64
		sourceColumn: orders

	column merchandise_value_brl
		dataType: double
		sourceColumn: merchandise_value_brl

	column average_order_value_brl
		dataType: double
		sourceColumn: average_order_value_brl

	column merchandise_value_mom_pct
		dataType: double
		sourceColumn: merchandise_value_mom_pct

	partition MonthlyPerformance = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataRoot & "\\monthly_performance.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"order_month", type date}, {"orders", Int64.Type}, {"merchandise_value_brl", type number}, {"average_order_value_brl", type number}, {"merchandise_value_mom_pct", type number}})
			in
				Typed
