table OperationalPriority

	measure 'Late Order GMV' = SUM(OperationalPriority[late_order_merchandise_value_brl])
		formatString: R$ #,##0.00

	measure 'Priority Orders' = SUM(OperationalPriority[orders])
		formatString: #,##0

	measure 'Priority Late Delivery Rate' = DIVIDE(SUMX(OperationalPriority, OperationalPriority[late_delivery_pct] * OperationalPriority[orders]), SUM(OperationalPriority[orders]) * 100)
		formatString: 0.00%

	measure 'Priority Average Review' = DIVIDE(SUMX(OperationalPriority, OperationalPriority[average_review_score] * OperationalPriority[orders]), SUM(OperationalPriority[orders]))
		formatString: 0.00

	measure 'Priority Low Review Rate' = DIVIDE(SUMX(OperationalPriority, OperationalPriority[low_review_order_pct] * OperationalPriority[orders]), SUM(OperationalPriority[orders]) * 100)
		formatString: 0.00%

	column priority_rank
		dataType: int64
		sourceColumn: priority_rank

	column entity_type
		dataType: string
		summarizeBy: none
		sourceColumn: entity_type

	column entity_name
		dataType: string
		summarizeBy: none
		sourceColumn: entity_name

	column orders
		dataType: int64
		sourceColumn: orders

	column merchandise_value_brl
		dataType: double
		sourceColumn: merchandise_value_brl

	column late_delivery_pct
		dataType: double
		sourceColumn: late_delivery_pct

	column late_order_merchandise_value_brl
		dataType: double
		sourceColumn: late_order_merchandise_value_brl

	column average_review_score
		dataType: double
		sourceColumn: average_review_score

	column low_review_order_pct
		dataType: double
		sourceColumn: low_review_order_pct

	partition OperationalPriority = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataRoot & "\\analysis_operational_priority.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"priority_rank", Int64.Type}, {"entity_type", type text}, {"entity_name", type text}, {"orders", Int64.Type}, {"merchandise_value_brl", type number}, {"late_delivery_pct", type number}, {"late_order_merchandise_value_brl", type number}, {"average_review_score", type number}, {"low_review_order_pct", type number}})
			in
				Typed
