table PaymentBehaviour

	measure 'Payment Value' = SUM(PaymentBehaviour[payment_value_brl])
		formatString: R$ #,##0.00

	measure 'Payment Orders' = SUM(PaymentBehaviour[orders])
		formatString: #,##0

	measure 'Average Installments' = DIVIDE(SUMX(PaymentBehaviour, PaymentBehaviour[average_installments] * PaymentBehaviour[orders]), SUM(PaymentBehaviour[orders]))
		formatString: 0.00

	column payment_type
		dataType: string
		summarizeBy: none
		sourceColumn: payment_type

	column payment_rows
		dataType: int64
		sourceColumn: payment_rows

	column orders
		dataType: int64
		sourceColumn: orders

	column payment_value_brl
		dataType: double
		sourceColumn: payment_value_brl

	column average_installments
		dataType: double
		sourceColumn: average_installments

	column order_penetration_pct
		dataType: double
		sourceColumn: order_penetration_pct

	partition PaymentBehaviour = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataRoot & "\\payment_behaviour.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"payment_type", type text}, {"payment_rows", Int64.Type}, {"orders", Int64.Type}, {"payment_value_brl", type number}, {"average_installments", type number}, {"order_penetration_pct", type number}})
			in
				Typed
