table SellerOperations

	measure 'Seller GMV' = SUM(SellerOperations[merchandise_value_brl])
		formatString: R$ #,##0.00

	measure 'Seller Orders' = SUM(SellerOperations[orders])
		formatString: #,##0

	measure 'Priority Sellers' = CALCULATE(COUNTROWS(SellerOperations), SellerOperations[operational_status] = "review_priority")
		formatString: #,##0

	column seller_id
		dataType: string
		summarizeBy: none
		sourceColumn: seller_id

	column seller_state
		dataType: string
		summarizeBy: none
		sourceColumn: seller_state

	column orders
		dataType: int64
		sourceColumn: orders

	column merchandise_value_brl
		dataType: double
		sourceColumn: merchandise_value_brl

	column late_delivery_rate_pct
		dataType: double
		sourceColumn: late_delivery_rate_pct

	column average_review_score
		dataType: double
		sourceColumn: average_review_score

	column operational_status
		dataType: string
		summarizeBy: none
		sourceColumn: operational_status

	partition SellerOperations = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataRoot & "\\seller_operational_review.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"seller_id", type text}, {"seller_state", type text}, {"orders", Int64.Type}, {"merchandise_value_brl", type number}, {"late_delivery_rate_pct", type number}, {"average_review_score", type number}, {"operational_status", type text}})
			in
				Typed
