table StatePerformance

	measure 'State GMV' = SUM(StatePerformance[merchandise_value_brl])
		formatString: R$ #,##0.00

	measure 'State Orders' = SUM(StatePerformance[orders])
		formatString: #,##0

	measure 'State Customers' = SUM(StatePerformance[unique_customers])
		formatString: #,##0

	measure 'State Average Order Value' = DIVIDE(SUM(StatePerformance[merchandise_value_brl]), SUM(StatePerformance[orders]))
		formatString: R$ #,##0.00

	column customer_state
		dataType: string
		summarizeBy: none
		sourceColumn: customer_state

	column orders
		dataType: int64
		sourceColumn: orders

	column unique_customers
		dataType: int64
		sourceColumn: unique_customers

	column merchandise_value_brl
		dataType: double
		sourceColumn: merchandise_value_brl

	column average_order_value_brl
		dataType: double
		sourceColumn: average_order_value_brl

	column late_delivery_pct
		dataType: double
		sourceColumn: late_delivery_pct

	column average_review_score
		dataType: double
		sourceColumn: average_review_score

	partition StatePerformance = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(DataRoot & "\\state_performance.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"customer_state", type text}, {"orders", Int64.Type}, {"unique_customers", Int64.Type}, {"merchandise_value_brl", type number}, {"average_order_value_brl", type number}, {"late_delivery_pct", type number}, {"average_review_score", type number}})
			in
				Typed
