version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: customers
        columns:
          - name: customer_id
            tests: [not_null, unique]
      - name: orders
        columns:
          - name: order_id
            tests: [not_null, unique]
          - name: customer_id
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'customers')
                  field: customer_id
      - name: order_items
        columns:
          - name: order_id
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'orders')
                  field: order_id
      - name: payments
        columns:
          - name: order_id
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'orders')
                  field: order_id
      - name: reviews
        columns:
          - name: order_id
            tests:
              - not_null
              - relationships:
                  to: source('raw', 'orders')
                  field: order_id
