"""Build recruiter-facing code-first notebooks from the real project source files.

This keeps the production-style modular Python package while ensuring a recruiter
can open one notebook and immediately see the actual implementation rather than
having to hunt through run.py and src/*.py.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

PROJECTS = {
    "flight_delay_risk": {
        "title": "Flight Delay Risk Platform — Full Python Code",
        "dataset": "U.S. DOT/BTS On-Time Reporting Carrier On-Time Performance data, with a temporal 2026 holdout documented in DATA_CARD.md.",
        "files": [
            "run.py",
            "api.py",
            "src/data.py",
            "src/features.py",
            "src/model.py",
            "src/pipeline.py",
            "src/evaluate.py",
            "src/inference.py",
        ],
    },
    "ecommerce_sql_analytics": {
        "title": "E-commerce SQL + dbt Analytics — Full Python Code",
        "dataset": "Olist Brazilian E-commerce public dataset (pinned/reproducible download in src/data.py).",
        "files": [
            "run.py",
            "src/config.py",
            "src/data.py",
            "src/warehouse.py",
            "src/validate.py",
            "dbt_project/prepare_fixture.py",
        ],
    },
    "executive_commerce_bi": {
        "title": "Executive Commerce Intelligence — Full Python Code",
        "dataset": "Governed Olist warehouse exports used by the Power BI and Tableau layer.",
        "files": [
            "prepare_bi_data.py",
            "business_analysis.py",
            "cohort_analysis.py",
            "enrich_tableau_analysis.py",
            "refresh_verified_data.py",
            "render_dashboard_preview.py",
        ],
    },
    "experiment_lab": {
        "title": "ExperimentLab — Full Python Code",
        "dataset": "Deterministic synthetic randomized-experiment data with a known treatment effect.",
        "files": ["run.py"],
    },
    "grounded_rag": {
        "title": "Grounded RAG — Full Python Code",
        "dataset": "Deterministic knowledge-base, retrieval, tool and evaluation fixtures defined in the project source.",
        "files": ["run.py", "api.py"],
    },
    "model_watch": {
        "title": "ModelWatch — Full Python Code",
        "dataset": "Deterministic reference and shifted monitoring batches generated by the project.",
        "files": ["run.py"],
    },
    "reliable_event_pipeline": {
        "title": "Reliable Event Pipeline — Full Python Code",
        "dataset": "Committed event fixtures in fixtures/batch_1.csv and fixtures/batch_2.csv.",
        "files": ["run.py", "src/pipeline.py"],
    },
    "retail_customer_segmentation": {
        "title": "Retail Customer Segmentation — Full Python Code",
        "dataset": "UCI Online Retail; raw workbook is downloaded reproducibly by src/data.py.",
        "files": [
            "run.py",
            "src/data.py",
            "src/features.py",
            "src/model.py",
            "src/evaluation.py",
        ],
    },
}


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}


def code(text: str, *, source_mirror: bool = False) -> dict:
    metadata = {"tags": ["source-mirror", "skip-execution"]} if source_mirror else {}
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": metadata,
        "outputs": [],
        "source": text.splitlines(keepends=True),
    }


def build_notebook(slug: str, spec: dict[str, object]) -> dict:
    project_dir = ROOT / "projects" / slug
    cells: list[dict] = []
    cells.append(md(
        f"# {spec['title']}\n\n"
        "**Hiring purpose:** one project, one notebook, with the actual Python implementation visible. "
        "The modular files remain in the repository because that is how production code should be organised; "
        "this notebook mirrors those files so a recruiter can inspect the full code without hunting.\n"
    ))
    cells.append(md(
        "## Dataset and reproducibility\n\n"
        f"{spec['dataset']}\n\n"
        "The project README/data card documents provenance, constraints and the exact reproduction path. "
        "Large third-party raw files are not duplicated in Git when licensing or repository size makes that poor engineering practice.\n"
    ))
    cells.append(code(
        "from pathlib import Path\n"
        "import json, os, subprocess, sys\n\n"
        f"PROJECT_SLUG = {slug!r}\n"
        "ROOT = Path.cwd()\n"
        "if not (ROOT / 'projects').exists():\n"
        "    target = Path('/content/uni_projects')\n"
        "    if not target.exists():\n"
        "        subprocess.run(['git', 'clone', 'https://github.com/Jorgoluka100/uni_projects.git', str(target)], check=True)\n"
        "    os.chdir(target)\n"
        "    ROOT = target\n"
        "PROJECT = ROOT / 'projects' / PROJECT_SLUG\n"
        "assert PROJECT.exists(), PROJECT\n"
        "print('Project:', PROJECT.resolve())\n"
    ))
    cells.append(md(
        "## Full Python implementation\n\n"
        "Every code cell below is copied directly from the corresponding `.py` file on the same commit. "
        "These cells are intentionally tagged `source-mirror` so the notebook acts as a readable code portfolio while the canonical modules remain testable files.\n"
    ))

    mirrored = 0
    for rel in spec["files"]:
        path = project_dir / str(rel)
        if not path.exists():
            raise FileNotFoundError(path)
        cells.append(md(f"### `{rel}`\n"))
        cells.append(code(path.read_text(encoding="utf-8"), source_mirror=True))
        mirrored += 1

    cells.append(md(
        "## Run the real project\n\n"
        "The cell below executes the canonical project entry point rather than a rewritten toy version. "
        "Keep `RUN_PIPELINE = False` when you only want to inspect the notebook; change it to `True` to reproduce the project.\n"
    ))
    cells.append(code(
        "RUN_PIPELINE = False\n"
        "if RUN_PIPELINE:\n"
        "    subprocess.run([sys.executable, 'run.py'], cwd=PROJECT, check=True)\n"
        "else:\n"
        "    print(f'Reproduce with: cd {PROJECT} && python run.py')\n"
    ))
    cells.append(code(
        "evidence = []\n"
        "for folder in (PROJECT / 'results', ROOT / 'verified' / PROJECT_SLUG):\n"
        "    if folder.exists():\n"
        "        evidence.extend(sorted(folder.glob('*.json')))\n"
        "for path in evidence[:5]:\n"
        "    print('\\n---', path.relative_to(ROOT), '---')\n"
        "    print(path.read_text(encoding='utf-8')[:12000])\n"
    ))
    cells.append(md(
        "## Interview discussion\n\n"
        "Be ready to explain the business problem, dataset provenance, cleaning/preprocessing decisions, leakage controls, "
        "modelling or analytical choices, evaluation design, limitations, testing strategy and what you would change in production. "
        "The key signal is that the notebook, modular source, tests and retained evidence all tell the same story.\n"
    ))

    if mirrored < 1:
        raise AssertionError(f"No Python files mirrored for {slug}")
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    changed: list[str] = []
    for slug, spec in PROJECTS.items():
        target = ROOT / "projects" / slug / "project_notebook.ipynb"
        content = json.dumps(build_notebook(slug, spec), indent=1, ensure_ascii=False) + "\n"
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            target.write_text(content, encoding="utf-8")
            changed.append(str(target.relative_to(ROOT)))
    print(json.dumps({"updated": changed, "count": len(changed)}, indent=2))


if __name__ == "__main__":
    main()
